name: Lint WorkFlow

on: [push, pull_request]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format